global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "sipserver"
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:8080"]


  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
